---
collections:
  # Required for molecule testing
  # v3.10.3 or higher due to python requests issue
  - name: community.docker
  # Needed for latest bitwarden_secrets_manager
  - name: community.general
roles:
  - name: stefangweichinger.ansible_rclone
