---
- name: "Install the various proxmox roles"
  hosts: all
  pre_tasks:
    - name: Verify Ansible is version 2.15 or above. (If this fails you may need to update Ansible)
      assert:
        that: "ansible_version.full is version_compare('2.15', '>=')"
        msg: >
          "Ansible is out of date."
