---
collections:
  # Required for molecule testing
  # v3.10.3 or higher due to python requests issue
  - name: community.docker
    version: "3.12.1"
  - name: bitwarden.secrets
    version: "1.0.0"
roles:
  - name: stefangweichinger.ansible_rclone
    version: "0.2.0"
