---
dependency:
  name: galaxy
  options:
    requirements-file: meta/requirements.yml
    role-file: meta/requirements.yml
driver:
  name: docker
platforms:
  - name: "rclone-${image:-debian12}-${tag:-latest}-${TOX_ENVNAME}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    host_vars:
      instance:
        rclone_release: ${TEST_RELEASE:-stable}
        rclone_version: ${TEST_VERSION:-''}
